#!/usr/bin/env bash
set -eu
set -o pipefail

# Constants
declare -r FIRMWARE_URL=https://www.kraxel.org/repos/jenkins/edk2/edk2.git-ovmf-x64-0-20200515.1413.g627d1d6693.noarch.rpm

# Globals
declare g_destination=
declare g_temp_dir=

main() {
  trap unmain EXIT

  g_destination=$(readlink --canonicalize "$(dirname "${BASH_SOURCE[0]}")")/_assets/ovmf/

  g_temp_dir=$(mktemp -d)
  cd "${g_temp_dir}"

  printf "Downloading firmware...\n"
  curl -s "${FIRMWARE_URL}" > ovmf.rpm

  printf "Extracting firmware from RPM...\n"
  rpm2cpio ./ovmf.rpm | cpio -idmv

  printf "Copying to destination...\n"
  mkdir -p "${g_destination}"
  cp -f ./usr/share/edk2.git/ovmf-x64/OVMF-pure-efi.fd "${g_destination}/code.fd"
  cp -f ./usr/share/edk2.git/ovmf-x64/OVMF_VARS-pure-efi.fd "${g_destination}/vars.fd"
}

unmain() {
  if [[ -n "${g_temp_dir}" ]] && [[ -d "${g_temp_dir}" ]]
  then
    rm -rf "${g_temp_dir}"
  fi
}

main

