[package]
name = "osc-os-boot-stub"
version = "0.1.0"
authors = ["philipstears <philip@philipstears.com>"]
edition = "2018"

[dependencies]
rlibc = "1.0.0"
uefi = { version = "0.4.6", features = [ "alloc" ] }

[patch.crates-io]
uefi = { path = "../../../third/uefi-rs" }
